justinwoo/easy-purescript-nix

Makefile
default.nix
spacchetti-cli.nix
spago.nix

add spago derivation and add note about spacchetti-cli deprecation

---

spago.nix

update spago to 0.6.2.1

---

ci.nix
default.nix

Howdy! I'd like to use this for a project, but would like to specify the package set to build things from. Are you willing to accept a change to allow setting the package set?

Allow setting the `nixpkgs`

---

spago.nix

I'm sure you'd have got round to this pretty quickly but I was doing it anyway :smile:

Bump Spago version to 0.9.0.0

---

default.nix
purs/0.13.0.nix
purs/0.13.2.nix
purs/mkPursDerivation.nix

expose multiple purescript versions

---

.github/workflows/ci.yml
.travis.yml
ci.nix

This boots up faster than Travis and runs in less time. It still uses yaml though

Use GitHub Actions for CI

---

psc-package-simple.nix
zephyr.nix

This PR fills in some missing darwin bits to the point where nix-shell works.

Get zephyr and psc-package working on darwin

---

pscid/default.nix

Bumps pscid to v2.9.2

---

README.md

(minor) for people that copy paste the README example

Update Readme: Current purs version, recent revision

---

README.md

Thank you for making this (and all your other great projects and resources)!

Some `nix-shell`-related suggestions

---

purty.nix

Updating to purty formatter from 6.2 to recently released 7.0

Update purty to 7.0.0

---

ci.nix
default.nix
purty.nix
tests.bash

We are using npm registry as a binary source for pury.

Re-add purty

---

default.nix
purs/0.14.4.nix

https://github.com/purescript/purescript/releases/tag/v0.14.4

purs: 0.14.3 → 0.14.4

---

purs-tidy/default.nix
purs-tidy/node-packages.nix

https://github.com/natefaubion/purescript-tidy/releases/tag/v0.6.3

purs-tidy: 0.6.2 → 0.6.3

---

purescript-language-server/default.nix
purescript-language-server/node-packages.nix

https://github.com/nwolverson/purescript-language-server/releases/tag/v0.16.0

purescript-language-server: 0.15.8 → 0.16.0

---

purs-tidy/default.nix
purs-tidy/node-packages.nix

https://github.com/natefaubion/purescript-tidy/releases/tag/v0.6.4

purs-tidy: 0.6.3 → 0.6.4

---

purescript-language-server/default.nix
purescript-language-server/node-packages.nix

https://github.com/nwolverson/purescript-language-server/releases/tag/v0.16.2

purescript-language-server: 0.16.1 → 0.16.2

---

purescript-language-server/default.nix
purescript-language-server/node-packages.nix

https://github.com/nwolverson/purescript-language-server/releases/tag/v0.16.3
https://github.com/nwolverson/purescript-language-server/releases/tag/v0.16.4

purescript-language-server: 0.16.2 → 0.16.4

---

purescript-language-server/default.nix
purescript-language-server/node-packages.nix

https://github.com/nwolverson/purescript-language-server/releases/tag/v0.16.5

purescript-language-server: 0.16.4 → 0.16.5

---

purs/0.14.6.nix
purs/0.14.7.nix

Versioned symbols for ncurses

---

purs/0.15.0-alpha-02.nix

Here is Purescript v0.15.0-alpha-02 if you want it. Also with the necessary fix for the ncurses build.

Purescript 0.15.0-alpha-02

---

default.nix

Purescript 0.15.0-alpha-02 default.nix

---

default.nix
purs/0.15.0.nix

from https://github.com/justinwoo/easy-purescript-nix/pull/195
couldn't find an actual working workflow for updating the PR branch upstream

Purs 0.15.0

---

purs-tidy/default.nix
purs-tidy/node-packages.nix

2022-04-04: https://github.com/natefaubion/purescript-tidy/releases/tag/v0.7.2

purs-tidy: 0.7.1 → 0.7.2

---

purescript-language-server/default.nix
purescript-language-server/node-packages.nix

2022-03-21: https://github.com/nwolverson/purescript-language-server/releases/tag/v0.16.6

purescript-language-server: 0.16.5 → 0.16.6

---

default.nix
purs/0.14.9.nix

add purs 0.14.9

---

spago.nix

spago: 0.20.8 -> 0.20.9

---

purs-tidy/default.nix
purs-tidy/node-packages.nix

https://github.com/natefaubion/purescript-tidy/releases/tag/v0.9.0

purs-tidy: 0.7.2 → 0.9.0

---

flake.nix

The dhall in nixpkgs is more recent than the one in easy-dhall-nix

In .#deluxe use nixpkgs dhall

---

default.nix
purs/0.15.11.nix
purs/0.15.12.nix
purs/0.15.13.nix
purs/0.15.14.nix
purs/0.15.15.nix
purs/0.15.16-0.nix

```sh
array=(
0.15.16-0
0.15.15
0.15.14
0.15.13
0.15.12
0.15.11
)
owner="purescript"
repo="purescript"
for version in "${array[@]}"; do
cp "./purs/0.15.9.nix" "./purs/${version}.nix"
sed -i "s/0.15.9/${version}/" "./purs/${version}.nix"
x86_64_linux_url="https://github.com/$owner/$repo/releases/download/v$version/linux64.tar.gz"
echo "x86_64-linux_url=$x86_64_linux_url"
x86_64_darwin_url="https://github.com/$owner/$repo/releases/download/v$version/macos.tar.gz"
echo "x86_64_darwin_url=$x86_64_darwin_url"
aarch64_darwin_url="https://github.com/$owner/$repo/releases/download/v$version/macos-arm64.tar.gz"
echo "aarch64_darwin_url=$aarch64_darwin_url"
sed -i "s/0rabinklsd8bs16f03zv7ij6d1lv4w2xwvzzgkwc862gpqvz9jq3/$(nix-prefetch-url --quiet $x86_64_linux_url)/" "./purs/${version}.nix"
sed -i …
```

purs: 0.15.10 -> 0.15.15
