justinwoo/easy-purescript-nix

psc-package-simple.nix, purp.nix, purs.nix, spacchetti-cli.nix
The installed binaries now use nixpkgs dependencies. All installed
binaries seem to work on NixOS. This change makes all non-nixos systems
use libraries such as gmp and zlib from nixpkgs instead of their native
package systems.
=> Patchelf installed binaries to use libraries from nixpgks

purs/0.13.5.nix
The hash for https://github.com/purescript/purescript/releases/download/v0.13.5/macos.tar.gz was not matched.
=> Fix purs-0.13.5 hash mismatch on darwin

spago.nix
I'm experiencing an issue of spago place `output` folder in unexpected directory with current version. This PR updates spago to most recent version `0.13.1`
=> Update spago to 0.13.1

default.nix, purs/0.13.6.nix
There's a [new release of the PureScript compiler](https://github.com/purescript/purescript/releases/tag/v0.13.6), so I've added the new version to easy-purescript-nix and updated the default PureScript version to `purs-0_13_6`.
I've tested this by using `easy-purescript-nix` in a Nix shell pointing at my fork, then compiling a PureScript project using the resulting `purs` version 0.13.6, and things check out.
=> Add PureScript 0.13.6

zephyr.nix
Based on the [new release](https://github.com/coot/zephyr/releases/tag/v0.2.2). 
Zephyr was [updated to rely on PureScript 0.13](https://github.com/coot/zephyr/pull/21) a little while ago. Later, I discovered that the pre-0.13 version of Zephyr would, on projects with many modules (1000+) sometimes fail when trying to write a directory the compiler should have produced. The current version of Zephyr avoids this issue likely due to changes in the PureScript compiler.
=> Bump zephyr version to 0.2.2

spago.nix
Version 0.14.0 appears to be fetched in the definition already but the version number of the derivation wasn't updated. I modified the Nix so these would be consistent but kept the current Nix build result the same:
```sh
$ nix-build spago.nix
/nix/store/cl2apfqqspl8qbr5lywsfi29bdrbn6v0-spago
$ /nix/store/cl2apfqqspl8qbr5lywsfi29bdrbn6v0-spago/bin/spago version
0.14.0
$ nix-info
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.3.2, <redacted>, channels(root): "nixos-19.09.2036.c49da6435f3", <redacted>
```
=> Update spago version to version referenced in Nix definition

zephyr.nix
Another update for Zephyr, this time for 0.3.2.
```
[nix-shell:~/Desktop/easy-purescript-nix]$ zephyr --version
0.3.2
```
=> Update Zephyr for 0.3.2

.github/workflows/ci.yml
GitHub Actions has deprecated the `set-env` and `add-path` commands, which means that old versions of `install-nix-action` no longer work. 
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
This PR updates to the latest `install-nix-action`, which (since version 11) now requires a `nix_path`. I've set this to 20.09, but we can use something else if desired.
=> Update `install-nix-action` for CI

zephyr.nix
Fixes the following error when building `zephyr` using Nixpkgs 19.09:
```
these derivations will be built:
/nix/store/5xq1gnvzvq5wk2ydf4pixa90hkwbyc50-zephyr-0.3.2.drv
building '/nix/store/5xq1gnvzvq5wk2ydf4pixa90hkwbyc50-zephyr-0.3.2.drv'...
unpacking sources
install_name_tool: object: /nix/store/czckp29wprywjyh7pia4lhx5j16dsr0g-zephyr-0.3.2/bin/zephyr malformed object (unknown load command 10)
builder for '/nix/store/5xq1gnvzvq5wk2ydf4pixa90hkwbyc50-zephyr-0.3.2.drv' failed with exit code 1
error: build of '/nix/store/5xq1gnvzvq5wk2ydf4pixa90hkwbyc50-zephyr-0.3.2.drv' failed
```
=> Use `fixDarwinDylibNames` when building `zephyr`

spago.nix
https://github.com/purescript/spago/releases/tag/0.19.1
```sh
$ nix-prefetch-url "https://github.com/purescript/spago/releases/download/0.19.1/Linux.tar.gz"                  
[8.5 MiB DL]
path is '/nix/store/ni2kd76bfbfkzxh1w8dli5fnvp0z1c5y-Linux.tar.gz'
1i12kmaf2cr86aj1pdnxx8jf1l59k5k5vhwf80l1msdzqlbdbj14
$ nix-prefetch-url "https://github.com/purescript/spago/releases/download/0.19.1/macOS.tar.gz"                  
[3.7 MiB DL]
path is '/nix/store/araz8nrzmxc6ylvx0agcszx3kabc1qyj-macOS.tar.gz'
1wgz3l97by3mn6317wvvyks47bb87k0ij8hy32d29im4xq5fqi8s
```
=> Bump to spago v0.19.1

spago.nix
https://github.com/purescript/spago/releases/tag/0.19.2
```
$ nix-prefetch-url "https://github.com/purescript/spago/releases/download/0.19.2/macOS.tar.gz"                     
path is '/nix/store/r09yw8s08l4g86mf9zshdd9whi08nmpg-macOS.tar.gz'
0pjqs6bjp8ya9kxwgisdwrcbaqr730fsjzziqmkkh44q8jqcnfbp
$ nix-prefetch-url "https://github.com/purescript/spago/releases/download/0.19.2/Linux.tar.gz"                     
path is '/nix/store/23384l9if75k5qc4g9yg5pwjan1rq6a2-Linux.tar.gz'
0w8q0c2a4qdpdswdhmiv1bqlwjp5dwlb7kdrsgmsndif1hgpywi0
```
=> spago: 0.19.1 → 0.19.2

spago.nix
https://github.com/purescript/spago/releases/tag/0.20.0
```
$ nix-prefetch-url "https://github.com/purescript/spago/releases/download/0.20.0/macOS.tar.gz"                     
path is '/nix/store/hx0asxf09vhwjfnz68fd20j5fpdaxvhy-macOS.tar.gz'
1lxinqn5qnvgyn8iv9kyb2wyl8vpw8s5vkkmmygx9m0pzr9vlx7w
$ nix-prefetch-url "https://github.com/purescript/spago/releases/download/0.20.0/Linux.tar.gz"                     
path is '/nix/store/4ga3xka8zxb0z6hlqw1gh8aacags2rdf-Linux.tar.gz'
077r8dnxda8v92rpq018iwbh4b6m5af3wa6cdyg6gm61q4sjw03k
```
=> spago: 0.19.2 → 0.20.0

spago.nix
https://github.com/purescript/spago/releases/tag/0.20.1
```
$ nix-prefetch-url "https://github.com/purescript/spago/releases/download/0.20.1/macOS.tar.gz"
path is '/nix/store/ck9l7bdhhgni00qivr397r5anvvypqcw-macOS.tar.gz'
0v47zb941hwmkx8jy3ql0bw3d7ailq4srqlk4c1fdw6gj9xylr5n
$ nix-prefetch-url "https://github.com/purescript/spago/releases/download/0.20.1/Linux.tar.gz"
path is '/nix/store/knqpizg8g8dq1m76n1bg56s1ygvdvqwb-Linux.tar.gz'
089270c36hf333hm5jc5vmjissjkfxmcihpkw7aiamvbb0gjg2h3
````
=> spago: 0.20.0 → 0.20.1

default.nix, purs/0.14.1.nix
https://github.com/purescript/purescript/releases/tag/v0.14.1
```
$ nix-prefetch-url "https://github.com/purescript/purescript/releases/download/v0.14.1/macos.tar.gz"
path is '/nix/store/rzn743da4khnbfrrcij4cdnlx3d11bij-macos.tar.gz'
1m2xpnf6npnp1dgwqd1fcfbl6nq1p2k7fbz0jsywx3d6hdn1w7hv
$ nix-prefetch-url "https://github.com/purescript/purescript/releases/download/v0.14.1/linux64.tar.gz"
path is '/nix/store/6ndylbmzhyfhlwgsrgq8mccv0isc68lh-linux64.tar.gz'
1j3g5l0aqqfw8clra36ddnl55ir9k8yqbndnp04ya7s4vwr1hr2v
```
=> purs 0.14.1

spago.nix
https://github.com/purescript/spago/releases/tag/0.20.2
```
$ nix-prefetch-url "https://github.com/purescript/spago/releases/download/0.20.2/macOS.tar.gz"
path is '/nix/store/3qgpbddhyjkd39pxv8lbjlj1v3aag58s-macOS.tar.gz'
0smdhaccxibhz0hywyfy7vp6y6s38gqq46nri8yxdvnk6aqgdjvr
$ nix-prefetch-url "https://github.com/purescript/spago/releases/download/0.20.2/Linux.tar.gz"
path is '/nix/store/27dl8phcfrn9pcfgswc3psyk1wrf2ibb-Linux.tar.gz'
0d4x1g2fgi6fpdp0fq8bdg7jd587l7dffwrycf8mqwlsaxq8vfy9
```
=> spago: 0.20.1 → 0.20.2

spago2nix.nix
There's still a big flaw in that this is _not_ compatible with the latest spago because of `list-pacakges` vs `ls`, but at least this is the version from the latest main branch
=> spago2nix: 898798204fa8f53837bbcf71e30aeb425deb0906

default.nix, purs/0.14.2.nix
https://github.com/purescript/purescript/releases/tag/v0.14.2
```console
$ nix-prefetch-url "https://github.com/purescript/purescript/releases/download/v0.14.2/linux64.tar.gz"
path is '/nix/store/7x3anmcj2m0l0zllairyymai5a06phb3-linux64.tar.gz'
1kv7dm1nw85lw3brrclkj7xc9p021jx3n8wgp2fg3572s86ypskw
$ nix-prefetch-url "https://github.com/purescript/purescript/releases/download/v0.14.2/macos.tar.gz"
path is '/nix/store/wvfp718kjxqa0xab07jcr7mrprlbmdaa-macos.tar.gz'
1ga2hn9br71dyzn3p9jvjiksvnq21p6i5hp1z1j5fpz9la28nqzf
```
=> purs: 0.14.1 → 0.14.2

default.nix, purs/0.14.3.nix
https://github.com/purescript/purescript/releases/tag/v0.14.3
```console
$ nix-prefetch-url "https://github.com/purescript/purescript/releases/download/v0.14.3/linux64.tar.gz"             
path is '/nix/store/0fnw9k854qn30pnw9b82zbvf7nilwqdc-linux64.tar.gz'
158jyjpfgd84gbwpxqj41mvpy0fmb1d1iqq2h42sc7041v2f38p0
$ nix-prefetch-url "https://github.com/purescript/purescript/releases/download/v0.14.3/macos.tar.gz"               
path is '/nix/store/dddg704ndg28vqis5v864yrknvrzhhrx-macos.tar.gz'
1ipksp6kx3h030xf1y3y30gazrdz893pklanwak27hbqfy3ckssj
```
---
I would appreciate if I could get some feedback on my other PR #146 because I can't work with this on Nix unstable because of `stdenv.lib` being deprecated and the old  `node2nix` version `1.8.0` using it; that PR reran `node2nix 1.9.0` on all …
=> purs: 0.14.2 → 0.14.3

zephyr.nix
A minor fix to bring pull the Zephyr version into a separate variable as is standard practice in this repo and `nixpkgs`
=> Use ${version} in Zephyr

purs-tidy/default.nix
I goofed. These are easy to forget which is which. A user didn't have `node` already on the path unlike myself an the tests for this repo.
I also provided a default `purs`, but I'm not sure if this is the best way to do it.
Closes smilack's [Discourse issue](https://discourse.purescript.org/t/announcing-purs-tidy-a-syntax-tidy-upper-for-purescript/2524/15)
=> Swap buildInput and nativeBuildInput for `purs-tidy`

purs-tidy/default.nix, purs-tidy/spago-packages.nix
I got some clarification on what the versions should be. The were added
to the `purs-tidy` README, and I added as comments to help anyone
needing to update in the future.
=> purs-tidy: 0.4.0 → 0.4.1

purs-tidy/default.nix, purs-tidy/spago-packages.nix
remove unnecessary `ls` and uses `fetchFromGitHub` which gets the
tarball — which is faster. Also adding more comments about how to
upgrade spago packages.
Upgrade: 0.4.1 → 0.4.2
https://github.com/natefaubion/purescript-tidy/releases/tag/v0.4.2
=> purs-tidy: 0.4.1 → 0.4.2 + clean up 

purs-tidy/default.nix, purs-tidy/node-packages.nix
https://github.com/natefaubion/purescript-tidy/releases/tag/v0.5.3
- Fixes issues where comments can affect formatting in unintentional
ways
0.5.2 had no changes for the tool
=> purs-tidy: 0.5.1 → 0.5.3

spago2nix.nix
Matches the API for the node2nix-generated packages in making this overridable. Could fix issues in the future when 12 and 14 get deprecated and people need a fast way to get up and running again. I tested v14 on my machine to override v10 via this patch and it worked for me.
=> Make spago2nix’s nodejs overridable

purs-tidy/default.nix, purs-tidy/node-packages.nix
https://github.com/natefaubion/purescript-tidy/releases/tag/v0.7.0
Also, moving from Node 12 to 14 as very soon, 12 will be end-of-life
(2022-04-30).
=> purs-tidy: 0.6.4 → 0.7.0

spago.nix
https://github.com/purescript/spago/releases/tag/0.20.4
```shell-session
$ nix-prefetch-url "https://github.com/purescript/spago/releases/download/0.20.4/Linux.tar.gz"
path is '/nix/store/jfmqwxlznyvrjlpggdq26f9fw111rqi5-Linux.tar.gz'
0qskajlc6a37gmwn9agadl824x781icf1876r558fji6g98xpb82
$ nix-prefetch-url "https://github.com/purescript/spago/releases/download/0.20.4/macOS.tar.gz"
path is '/nix/store/625g8ca33s4d945xsb6lf576l3gjvw5q-macOS.tar.gz'
0w7mrsxkk2gzb6png9j2nyi3h5d3ziaqjg98v0wp2klynafj8fmv
```
=> spago: 0.20.3 → 0.20.4

spago.nix
https://github.com/purescript/spago/releases/tag/0.20.5
```shell-session
$ nix-prefetch-url "https://github.com/purescript/spago/releases/download/0.20.5/macOS.tar.gz"
path is '/nix/store/nq4n4i1d1c83zs30zr608vsy97lw3f9s-macOS.tar.gz'
0yg4nbnngjfzihy86m5qcvi4zmpyfd4x8260x5jq7pb376bblan2
$ nix-prefetch-url "https://github.com/purescript/spago/releases/download/0.20.5/Linux.tar.gz"
path is '/nix/store/qymmw2170bzh6fzdsiy2xx6lw2r5s3fz-Linux.tar.gz'
1k1c22qv3g30f5awggdjiwxi7aifssfmcvnpjk391cssihj9k2y0
```
=> spago: 0.25.4 → 0.25.5

spago.nix
https://github.com/purescript/spago/releases/tag/0.20.7
```console
$ nix-prefetch-url "https://github.com/purescript/spago/releases/download/0.20.7/Linux.tar.gz"
path is '/nix/store/vdmvldzcyx8v54wkxxd4qipy13i0msjn-Linux.tar.gz'
0bh15dr1fg306kifqipnakv3rxab7hjfpcfzabw7vmg0gsfx8xka
$ nix-prefetch-url "https://github.com/purescript/spago/releases/download/0.20.7/macOS.tar.gz"
path is '/nix/store/c6837lfjigbmnc99i3s7pn7v7mgbxnzf-macOS.tar.gz'
0s5zgz4kqglsavyh7h70zmn16vayg30alp42w3nx0zwaqkp79xla
```
=> spago: 0.20.5 → 0.20.7

default.nix, purs/0.14.6.nix, purs/0.14.7.nix
`0.14.6` - https://github.com/purescript/purescript/releases/tag/v0.14.6
```
$ nix-prefetch-url "https://github.com/purescript/purescript/releases/download/v0.14.6/macos.tar.gz"
[6.0 MiB DL]
path is '/nix/store/03nss7dmvnrdda4zwpff53pmbc1mb6g6-macos.tar.gz'
0yfl4galaqzbbkql2vfsg4zrc5cv037286764kv8qibdk2yrhap3
$ nix-prefetch-url "https://github.com/purescript/purescript/releases/download/v0.14.6/linux64.tar.gz"
[10.3 MiB DL]
path is '/nix/store/l9blmc7dx92wj9wqy3a2xz0vrfba963m-linux64.tar.gz'
01mf850a9jhqba6a3hsbl9fjxp2khplwnlr15wzp637s5vf7rd79
```
`0.14.7` - https://github.com/purescript/purescript/releases/tag/v0.14.7
```
$ nix-prefetch-url "https://github.com/purescript/purescript/releases/download/v0.14.7/macos.tar.gz"
[6.0 MiB DL]
path is …
```
=> Add purs 0.14.6 and 0.14.7

default.nix, purs/0.15.0.nix
https://github.com/purescript/purescript/releases/tag/v0.15.0
```console
$ ~ nix-prefetch-url "https://github.com/purescript/purescript/releases/download/v0.15.0/linux64.tar.gz"
path is '/nix/store/wxvzbki12ygns35gn6lql65gkhp0jn76-linux64.tar.gz'
1ygp6wvbgl3y15wq1q41j9kg2ndaxr32rpgbzfzyd9zb8n9z8lpx
$ ~ nix-prefetch-url "https://github.com/purescript/purescript/releases/download/v0.15.0/macos.tar.gz"
path is '/nix/store/p7zplc54ysghhpg4vvs541xi8zk4yric-macos.tar.gz'
09d9pwba6fzc08m3nkc7xni29yr12gw5fj00aa77n9kxmsba0fkb
```
=> purs: 0.14.7 → 0.15.0

spago.nix
2022-04-27: https://github.com/purescript/spago/releases/tag/0.20.8
```console
$ nix-prefetch-url "https://github.com/purescript/spago/releases/download/0.20.8/Linux.tar.gz"
path is '/nix/store/nv2hb5hwi82ix420z0ll1hjash98ayvr-Linux.tar.gz'
1ihz44y6izg3nm391ms0cabv7i2g4n9ncvql4z8xpkg79r7s0vhr
$ "https://github.com/purescript/spago/releases/download/0.20.8/macOS.tar.gz"
path is '/nix/store/9sdnwr1ynafc02va12cmb7hzi2sb9i53-macOS.tar.gz'
10csxf27af303wkg216mz9x5wr5yylbwzk8lsg9f19hnav2x4c07
```
=> spago: 0.20.7 → 0.20.8

zephyr.nix
- zephyr: 0.3.2 → 0.4.0
- fix zephyr derivation: update ncurses, add cc lib
from #199
=> zephyr 0.4.0

zephyr.nix
https://github.com/MaybeJustJames/zephyr/tree/v0.4.0
```console
$ nix-prefetch-url "https://github.com/MaybeJustJames/zephyr/releases/download/v0.4.0/Linux.tar.gz"
path is '/nix/store/dvzgql0bnrpc6j15vvnawk10n6sp302j-Linux.tar.gz'
002rlf9s81il5x3adv7qhj0wxbnvv348l5rcllkrbivk008bb83x
$ nix-prefetch-url "https://github.com/MaybeJustJames/zephyr/releases/download/v0.4.0/macOS.tar.gz"
path is '/nix/store/h42zi21304qy7gysla9q5wn2y5jn765l-macOS.tar.gz'
```
=> zephyr: 0.3.2 → 0.4.0

default.nix, purs/0.15.3.nix
```console
$ nix-prefetch-url "https://github.com/purescript/purescript/releases/download/v0.15.3/linux64.tar.gz"
path is '/nix/store/wgf97fn7r3d1wk52ap9aasx3dz3a0234-linux64.tar.gz'
083pd5l0q2dj4ky9r4sgnfiinlch73qcvl3l26jf3nfs48y8hffv
$ nix-prefetch-url "https://github.com/purescript/purescript/releases/download/v0.15.3/macos.tar.gz"
path is '/nix/store/g3mqvhy5kgb4mwbwb924jmjm2az0vd3f-macos.tar.gz'
01ka3j1aakcabw6kmkfbk4c2cl2prihk6g8zvc995l83snj4n403
```
=> purescript: 0.15.2 → 0.15.3

default.nix, purs/0.15.6.nix
https://github.com/purescript/purescript/releases/tag/v0.15.6
```console
$ nix-prefetch-url "https://github.com/purescript/purescript/releases/download/v0.15.6/linux64.tar.gz"
path is '/nix/store/xl68m65ryxrlvd62b5d6w3xaabc1n79x-linux64.tar.gz' 
1vw3igxv4zr5gf1ml5ls17w9cc9shdn8fvbk6dkfnxrs93cwrq0k
$ nix-prefetch-url "https://github.com/purescript/purescript/releases/download/v0.15.6/macos.tar.gz" 
path is '/nix/store/5sfla8242ik04lgqzfs4m17sqr4i9b3f-macos.tar.gz' 
14l4m9xgp9slg4hfaqkwvzdvmg26qj2livldni3lmivvcagjgb2x
```
=> purescript: 0.15.4 → 0.15.6

default.nix, purs/0.15.7.nix
https://github.com/purescript/purescript/releases/tag/v0.15.7
```sh-session
$ nix-prefetch-url "https://github.com/purescript/purescript/releases/download/v0.15.7/macos.tar.gz"
path is '/nix/store/f53v70j9aqzagkgrwwgksp4f4604swlf-macos.tar.gz'
0aq5sr93z6c5l76sqbj3g48z6yrhxfqxri0x1ajmjwhcwjg79d6v
$ nix-prefetch-url "https://github.com/purescript/purescript/releases/download/v0.15.7/linux64.tar.gz"
path is '/nix/store/43p09j0gs8hfm3vdsqdyimhi09v3rjjz-linux64.tar.gz'
032jqrk46k9zbq058ms8rnrq0209rd8vkxwj73vqrlgqvpzlfl5k
```
=> purs: 0.15.6 → 0.15.7

zephyr.nix
```console
$ nix-prefetch-url "https://github.com/MaybeJustJames/zephyr/releases/download/v0.5.0/Linux.tar.gz"             
path is '/nix/store/h1kihn9xk19vgc4w6s51m3jxzcy858k3-Linux.tar.gz'
1c44nddlx7hx097klfslhap717fkah20vgf1phsp0gj8imjyvr0h
$ nix-prefetch-url "https://github.com/MaybeJustJames/zephyr/releases/download/v0.5.0/macOS.tar.gz"             
path is '/nix/store/8kaazcdh6psgkhz9dwnbp37vfkvyikac-macOS.tar.gz'
1qpd0mwnvkxygby467cr0zwcrpwnv9f0s99g7w8hfz0zfcg358bg
```
=> zephyr: 0.4.0 → 0.5.0

flake.nix
<pre>$ nix develop .#deluxe
<b>easy-purescript-nix deluxe development environment</b>
<b>See https://discourse.purescript.org/t/recommended-tooling-for-purescript-in-2022</b>
purs 0.15.9              Pulp version 16.0.2      psc-package 0.6.2      
spago 0.21.0             psa 0.8.2                pscid 2.10.0           
purs-tidy v0.10.0        purs-backend-es v1.3.2   Purty version: 7.0.0   
node v18.16.0            esbuild 0.17.19          zephyr 0.5.0           
bower 1.8.14             purescript-language-server 0.17.1               
</pre>
=> deluxe shell psa and print versions

default.nix, purs/0.15.10.nix
Hi there,
I've added `purescript` `v0.15.10` which was released a couple of days ago. I also added the `aarch64-darwin` binary which will remove the warning:
```
Using the non-native x86_64-darwin binary. While this binary may run under Rosetta 2 translation, no guarantees can be made about stability or performance.
```
I also took the liberty to enable the `aarch64-darwin` architecture for `0.15.9` which was [the first release providing the build](https://github.com/purescript/purescript/releases/tag/v0.15.9). The only remaining package in `easy-purescript-nix` that doesn't support the architecture is `zephyr`  https://github.com/MaybeJustJames/zephyr/issues/82 
When [commenting it out from the flake's shell](https://github.com/justinwoo/easy-purescript-nix/blob/master/flake.nix#L31) …
=> Upgrade to purs 0.15.10 and provide aarch64-darwin builds
